# Generated by Django 4.1.3 on 2022-12-17 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_settings_aboutus_alter_settings_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='keywods',
            new_name='keywords',
        ),
    ]
