# Generated by Django 4.1.3 on 2022-12-17 12:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0004_alter_images_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
