# Generated by Django 4.1.3 on 2022-12-17 12:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0005_category_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='detail',
        ),
        migrations.AlterField(
            model_name='content',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
