# Generated by Django 4.1.3 on 2022-12-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0006_remove_category_detail_alter_content_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
